#!/bin/bash
echo hello world
x=1
y=1
j=99999999
while [ $x -le 10000 ]
do
  echo "Welcome $x times"
  string=Performance_Br_$((x))
  git branch $string
  git checkout $string
  touch randomfile $i
  git add .
  git commit -m "ss"
  git push -u origin $string
  git push --set-upstream origin $string
  echo $string
  sleep 5.0
  x=$(( $x + 1 ))
done
