#!/bin/bash
echo hello world
x=1
y=1
j=1
while [ $x -le 10 ]
do
  echo "Welcome $x times"
  string=PPerformance_Br_$((x))
  git branch $string
  git checkout $string
  git add .
  git commit -m "s"
  git push -u origin $string
while [ $y -le 20 ]
do
  string="touch randfile$((j+x)) && git add . && git commit -m '$((j+x)):randfile_$((j+x))'"
  y=$(( $y + 1 ))
done
  git push -u origin $string
  git push --set-upstream origin $string
  echo $string
 #sleep 5.0
  x=$(( $x + 1 ))
done
